### ISSUE TITLE
US-24 - The system shall provide users with the abstract of each article - initial research

### ISSUE THREAD

**Issue by tristanhamid** [beedawn/scrapescholar#122]
Title: US-24
Priority: High
Estimation: 5
Risk: Low
Requirement: US-24

### User Story  
The system shall provide users with the abstract of each article

### Acceptance Criteria
Given a user logs into the application and performs a search
When the search results are returned to the user
Then the abstract is visible along with other elements of the search query. 

### Definition of Done
- [x] Initial research of API limitations completed

**Comment by tristanhamid** [comment]
I will need to do research about this item. When I was researching the API documentation in Sprint 1, it looks like the only way to retrieve the APIs is with a higher privledge API key which I think is behind a pay wall. 
One workaround that might work is I remember seeing an API that returns the abstract of any article (unsure if this was sciencedirect or scopus). To conform to the requirements of a minimum viable product, this might be acceptable but we will have to discuss with stakeholders that paid access will be required to effectively scale this application to meet their needs. 
Another issue that comes to mind is that this might slow down the application. If it does not, the API rate call limit will definitely need to be considered. I think it will be appropiate to hard code the API to only search for <5 abstracts that way we do not exceed our call limit.

**Comment by tristanhamid** [comment]
According to this documentation, there is no way to retrieve the abstract from the science direct articles
https://dev.elsevier.com/sd_search_views.html 

At this point, I will focus my efforts to testing Scopus articles only.

**Comment by tristanhamid** [comment]
Here is the Scopus documentation for Standard and Complete views:

https://dev.elsevier.com/sc_search_views.html

**Comment by tristanhamid** [comment]
Sent a message to Elsevier - Scopus - Reference number 241010-025677
"
Hello. I am wondering how I can get access to the Complete View of Scopus which includes the abstract. I am currently creating an internal application for researchers at Penn State University and part of the application requires the use of the abstract, author keywords, and other elements included in the Complete view of the API. 
https://dev.elsevier.com/sc_search_views.html
"

and also a message to Elsevier - ScienceDirect - Reference number 241010-025766
"
Hello.  I am currently creating an internal application for researchers at Penn State University and part of the application requires the use of the abstract, author keywords, and maybe other elements. Is there any way to recieve these attributes with the ScienceDirect API? It seems it is possible with Scopus and I am wondering why I can't find the same information with ScienceDirect. 
"

**Comment by tristanhamid** [comment]
Response from Elsevier
"
Thank you for contacting the Data Support team about access to the COMPLETE view in Scopus API. I'll be glad to assist.

I would like to share that full API access is only granted to clients that run within the networks of organizations that have subscriptions to the corresponding Elsevier product. Clients without subscriptions have access to limited basic metadata for most publications and citation records, as well as to basic search functionality.

Can you please tell me more about the work you are doing with the Research Products APIs? Once I have more information, I will be able to assist further.

-How much data do you need? (like around how many articles on the estimate?)
-What specific metadata are you looking to use?
-Are you only looking at data for your institution or will it include other institutions?
-How do you plan to manipulate it for your research? Please provide more details on the relationships you plan on exploring.
-What is the output of your research? Is it a paper or is it a web application?

Lastly, can you please share and paste your API key on your reply?

Thank you for your time and I will be waiting for your response.
"

and reply by me
"
We would like to search for up to 300 articles at a time. The current max limit for the Scopus API is 25. Is there any way around this?
Abstract and author keywords are the primary metadata I am focusing on, but information such as affiliation and funding agency might be helpful too. 
The application we are creating will only be used by Penn State University. It will not include any other institutions. 
The plan for the application is to return the most relevant articles to the Penn State researcher using our own algorithm. The app will use metadata from Scopus to determine the most relevant research articles (using both standard and complete metadata). 
The output is a web application that is used by Penn State University students and faculty to assist in their research efforts. It is a nonprofit effort. 
SCOPUS_APIKEY={I inserted my API key here}
"

**Comment by beedawn** [comment]
[Ticket Form - Penn State's IT Help Portal.pdf](https://github.com/user-attachments/files/17549477/Ticket.Form.-.Penn.State.s.IT.Help.Portal.pdf)

**Comment by beedawn** [comment]
I think we should work on containerizing the application before working on this more. This story will now require some kind of environment variable to enable or disable this feature set. It will also present complications with testing. Waiting until the docker containers are developed will simplify deployment and testing on the bigdata lab machine.
