### ISSUE TITLE
US-25 : Backend - The system shall provide users with a relevance score based on the ScrapeScholar algorithm used to analyze each abstract

### ISSUE THREAD

**Issue by tristanhamid** [beedawn/scrapescholar#124]
Title: US-25 Backend
Priority: High
Estimation: 8
Risk: Low
Requirement: US-25

### User Story  
The system shall provide uses with a relevance score based on the ScrapeScholar algorithm used to analyze each abstract

### Acceptance Criteria
Given a user logs into the application and performs a search
When the search results are returned to the user
Then the relevancy score is visible along with other elements of the search query. 

### Definition of Done
- [ ] Backend provides the abstract to the frontend by querying the respective database
- [ ] Backend provides the frontend with a dictionary of keywords paired with the most frequent words (sorted high to low)
- [ ] Backend database stores the abstract so that it can be retrieved in the future
- [ ] **Backend database stores the dictonary of keywords with each search query ???**
- [ ] Code is functional and complete 
- [ ] Unit tests are written, and pass 
- [ ] Integration tests are written, and pass 
- [ ] Automated tests pass 
- [ ] Automated build pass 
- [ ] GitHub Issue updated in a comment with any relevant documentation 
- [ ] Acceptance criteria are fully met

**Comment by tristanhamid** [comment]
Might be an XL task depending on how hard it is to display these relative sizes on the frontend

**Comment by beedawn** [comment]
weights probably need tweaking, but tests are written and basic functionality is implemented
