### ISSUE TITLE
Revisiting US-25: Optimization of Algorithm

### ISSUE THREAD

**Issue by tristanhamid** [beedawn/scrapescholar#154]
Currently our US-25 algorithm gives a relevance score but is not scalable to the number of keywords that our student researchers plan to use. The goal of this issue is to work to optimize the algorithm so that the stakeholders and use the search engine to fit their needs. 

The current algorithm takes approximately 10 seconds to return the relevance score for the searched articles. We assume that this time will scale linearly with each new additional keyword. With the example keywords given by the researchers there were approximately 15 keywords. We assume this search would take 150 seconds to perform (approx 2 and a half minutes). This will be the baseline to compare performance metrics.

**Comment by beedawn** [comment]
![Image](https://github.com/user-attachments/assets/eea95d75-ae0e-456f-9913-6f2c9fa52aa7)


data:
[data.json](https://github.com/user-attachments/files/17612558/data.json)

**Comment by tristanhamid** [comment]
After working this algorithm, I realize that I sacrificed too much accuracy in order to create a quicker algorithm. Moving this item back to Dependent on Work so that I can focus on other tasks, but may revisit the algorithm if there is enough time before the code freeze (Sunday December 24th)
