### ISSUE TITLE
Basic Automated Entry for Backend Functionality

### ISSUE THREAD

**Issue by tristanhamid** [beedawn/scrapescholar#17]
I plan to use python or java to make a simple back end that can access these databases for me. We still need to investigate (via stakeholder interviews) whether we will be using the Penn State library or IEEE. I think IEEE is better because it has an API. Also, this project (I forsee) could evolve into creating an API for Penn States library since it seems like one doesn't exist. I think that would be a good experience too.

**Comment by beedawn** [comment]
Closing for sprint
