### ISSUE TITLE
US-6 : FR6 - The system shall provide visualizations of metrics, such as the number of each marked color (red, yellow, green) and the progress of article review, and should update in real time based on the current view. 

### ISSUE THREAD

**Issue by beedawn** [beedawn/scrapescholar#24]
Priority: 7.5 Medium
Estimation: 8 
Risk: Low-Med
Title: US-6 
Requirement: R6

### User Story 
As a user, I want to see data visualizations such as how many articles are each color (red, yellow, green) and how many articles are left to review so that I can see how much progress has been made.

### Acceptance Criteria 
Given the user has submitted a search 
When a search view loads 
Then visualizations shown based on metrics such as color status, keyword occurrence, and article status (reviewed or not)

### Definition of Done
- [x] Frontend provides visualizations of statuses in a graph. 
- [x] Frontend provides visualizations of relevance rating occurrences in a bubble plot graph. 
- [x] Code is functional and complete. 
- [x] Unit tests are written, and pass. 
- [x] Integration tests are written, and pass. 
- [x] Automated tests pass. 
- [x] Automated build pass. 
- [x] GitHub Issue updated in a comment with any relevant documentation. 
- [x] Acceptance criteria are fully met.

**Comment by brilzen** [comment]
@beedawn @tristanhamid should we deprioritize and move this to sprint 4
