### ISSUE TITLE
US-8 : FR8 - The system shall allow users to export relevant search data to a csv file, that can easily be imported into excel. 

### ISSUE THREAD

**Issue by beedawn** [beedawn/scrapescholar#26]
Priority: 8.5 Medium/High 
Estimation: 8 
Risk: Low
Title: US-8 
Requirement: R8

### User Story 
As a user, I want to be able to export relevant visualizations, and article metrics to share with other users so that this information can be emailed or added to other documents.

### Acceptance Criteria 
Given a search has been rendered 
When user clicks a download button 
Then they are provided a csv file to download

### Definition of Done 
- [x] Frontend provides a button/link to download one to many searches  - Addressing in #64 
- [x] Backend provides the file(s) to download which can be captured from a GET request  
- [x] Code is functional and complete
- [x]  Unit tests are written, and pass 
- [x] Integration tests are written, and pass 
- [x] Automated tests pass Automated build pass
- [x]  GitHub Issue updated in a comment with any relevant documentation 
- [x] Acceptance criteria are fully met

**Comment by beedawn** [comment]
This will likely need to integrate with the database to pull all the data associated with the search such as color, and other user provided metrics.

**Comment by beedawn** [comment]
should we move this back to sprint 3?

**Comment by brilzen** [comment]
Yes that makes sense to move this to sprint 3

**Comment by tristanhamid** [comment]
That is okay for me, but will I still receive credit for my portion of the User Story?
________________________________

**Comment by tristanhamid** [comment]
Here is information that I was using during this sprint to generate the CSV. 

#   Create function to 'get' all elements needed for the front end and print results to a CSV
def json_to_csv(json_data):        
    file_path = "search_results_scopus.csv"
    with open(file_path, mode='w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(["Title","Year","Cited By","Link","Abstract","Document Type","Source", "Relevancy Score"])
        for entry in json_data["search-results"].get("entry", []):
            # Find URL link before parsing the rest of the data
            for link in entry.get("link", []):
                if link.get("@ref") == "scopus":
                    href_value = link.get("@href")
            # Classify the remaining attributes
            result = SearchResults(
                title = entry.get("dc:title"),
                year = str(entry.get("prism:coverDate", "Not Listed")[:4]),
                citedBy = entry.get("citedby-count"),
                link = href_value,
                abstract = None,       #Need to upgrade to view=COMPLETE (requires subscription?)
                documentType = entry.get("subtypeDescription"),
                source = "Scopus",
                relevanceScore = "0%"
            )
            rowArray = [result.title, result.year, result.citedBy, result.link, str(result.abstract), result.documentType, 
                        result.source, result.relevanceScore]
            writer.writerow(rowArray)
        file.close()
    return file_path

#  Access an environment variable for API Key
api_key = os.getenv("SCOPUS_APIKEY_TH")
