### ISSUE TITLE
US-9 : FR9 - The system shall allow users to leave notes on each article, with a maximum of 100 notes per article. 

### ISSUE THREAD

**Issue by beedawn** [beedawn/scrapescholar#27]
Priority:  9.5 High 
Estimation: 13
Risk: Low
Title: US-9 
Requirement: R9

### User Story 
As a user, I want to add notes and comments to articles so that I can reference them in the future and share with other users.

### Acceptance Criteria 
Given the user has selected an article in search results 
When the user selects to add a comment 
Then anyone who has access to the search can view the comment

### Definition of Done 
- [x] Frontend provides an interface to view, add, edit, and delete comments  
- [x] Frontend gets existing comments from database via a GET request to the backend  
- [x] Frontend provides POST request to backend to add new comments  
- [x] Frontend provides PUT request to backend to edit comments 
- [x] Frontend provides DELETE request to backend to delete comments 
- [x] Backend accepts POST request from frontend and adds POST request data to database to be used in future GET requests  
- [x] Backend accepts GET request from frontend and responds with article’s comments 
- [x] Backend accepts PUT request and modifies the database with the new comment 
- [x] Backend accepts DELETE request and deletes that specific comment 
- [x] Code is functional and complete 
- [x] Unit tests are written, and pass 
- [x] Integration tests are written, and pass 
- [x] Automated tests pass 
- [x] Automated build pass 
- [x] GitHub Issue updated in a comment with any relevant documentation 
- [ ] Acceptance criteria are fully met

**Comment by brilzen** [comment]
front end tests and limiting the number of comments per article are getting moved to a new story

**Comment by brilzen** [comment]
acceptance criteria only partially met because the front test are now part of https://github.com/beedawn/scrapescholar/issues/144
