### ISSUE TITLE
AR2 - The system shall provide a responsive user interface that accepts user input, actions, and adapts seamlessly to different screen sizes and devices, ensuring compatibility, usability, and a consistent user experience across platforms.

### ISSUE THREAD

**Issue by beedawn** [beedawn/scrapescholar#44]
Title: AR2 
Priority: Low
Estimation: 3 
Risk: Low
Requirement: AR2

## User Story  
The system shall provide a responsive user interface that accepts user input, actions, and adapts seamlessly to different screen sizes and devices, ensuring compatibility, usability, and a consistent user experience across platforms.
## Acceptance Criteria 
Given the user accesses the application via https://scrapescholar.me 
When the application receives and returns a response 
Then it should be compatible and usable from a variety of devices and interfaces such as mobile phones, and via a team's tab, and adapt the user interface to various screen sizes 

### Definition of Done
- [x] The user interface adapts across various screen sizes, including mobile phones, tablets, and desktops 
- [] ~~Cross-platform compatibility is tested and verified, including Microsoft Teams~~
- [x] User experience is consistent across all platforms and devices 
- [x] Unit and functional tests are written and passed 
- [x] Documentation is updated to include instructions and compatibility details for different devices and platforms. 
- [x] Code is reviewed, approved, and successfully deployed

**Comment by brilzen** [comment]
Part of the backlog grooming we decided this is a low priority based on team discussion on 10/6

**Comment by beedawn** [comment]
I think this will need bumped to 8 or 13 points as we have not been considering this in other user stories.

**Comment by beedawn** [comment]
Cannot test in teams as teams requires https cert to create a "tab". Since this is not deployed on our domain, will need to create another issue to create self signed cert for big data lab.
