### ISSUE TITLE
AR8 - The system shall utilize containerization for the backend application to ensure consistent and reliable deployment across different environments.

### ISSUE THREAD

**Issue by beedawn** [beedawn/scrapescholar#50]
Title: AR-8 
Priority: Medium 
Estimation: 5 
Risk: Low
Requirement: AR-8
## User Story  
The system shall utilize containerization for the backend application to ensure consistent and reliable deployment across different environments.
## Acceptance Criteria 
 Given a containerized setup for the backend application, 
When the container is built and deployed in any environment, 
Then the backend services should run consistently and function as expected, including database connections, API endpoints, and business logic.
### Definition of Done 
- [ ] Dockerfile for the backend application is created and reviewed. 
- [ ] Container is built and tested locally to ensure it runs as expected. 
- [ ] Deployment scripts or CI/CD pipelines for the containerized backend are created and validated. 
- [ ] Environment-specific configurations, such as database connections and API keys, are managed within the container or passed as environment variables. 
- [ ] Code and configuration are reviewed and approved. 
- [ ] Deployment is completed and validated in all target environments.

**Comment by beedawn** [comment]
@brilzen  is AR-8.3 completed for this, if so can the test traceability matrix be updated please?

**Comment by brilzen** [comment]
updated
