### ISSUE TITLE
AR10 - The system shall ensure that the persistent volume for the database is regularly backed up to a secure storage location to prevent data loss and enable recovery in case of system failure or data corruption.

### ISSUE THREAD

**Issue by beedawn** [beedawn/scrapescholar#52]
Title: AR-10 
Priority: Medium 
Estimation: 5 
Risk: Low
Requirement: AR-10

## User Story  
The system shall ensure that the persistent volume for the database is regularly backed up to a secure storage location to prevent data loss and enable recovery in case of system failure or data corruption.
## Acceptance Criteria  
Given a defined schedule (e.g., daily, weekly), 
When the backup job is triggered, 
Then the database should be backed up to a secure storage location without any data loss. 
Given a system failure or data corruption event, 
When a recovery process is initiated, 
Then the latest backup should be used to restore the database to a consistent state.
### Definition of Done 
- [ ] The backup schedule is configured and documented. 
- [x] Automated backup scripts or tools are implemented and tested. 
- [x] Backups are stored in a secure location with access controls. 
- [x] Recovery procedures are documented and tested. 
- [ ] Unit and integration tests are written for backup and recovery processes. 
- [ ] Code and configuration are reviewed and approved.

**Comment by beedawn** [comment]
This could be worked on in conjunction with the database container story.  #51

**Comment by beedawn** [comment]
Maybe copy from container to local machine with docker cp?

https://www.warp.dev/terminus/docker-copy-file-from-container-to-host

**Comment by brilzen** [comment]
powershell script to issue a docker exec to create the backup and docker cp to copy out the backup

**Comment by brilzen** [comment]
unable to run powershell script on BDL system, verified the steps in the test manually

![Image](https://github.com/user-attachments/assets/848d47f1-1cba-43b2-947d-43782876ba5a)

**Comment by brilzen** [comment]
here is a screenshot from the manual test 
![Image](https://github.com/user-attachments/assets/f0a6b71e-c350-454e-bad6-a02bf7e2a083)

**Comment by brilzen** [comment]
![Image](https://github.com/user-attachments/assets/f3cb0702-9fd2-4217-a1d4-a3de80ff68d4)

**Comment by beedawn** [comment]
@brilzen is AR-10.1 test case completed for this? If so can the test traceability matrix be updated please?

**Comment by brilzen** [comment]
@beedawn apologies for just getting back now I was driving
thanks for updating the traceability matrix for AR-10
I thought I had added 10.1 at least
